$(function(){
	//导航条菜单
	$(".b_k").find('li').mouseenter(function(){
		$(this).animate({'background-color':'#EEEEEE','border-radius':'10px','font-size':'18px'});
	});
	$(".b_k").find('li').mouseleave(function(){
		$(this).animate({'background-color':'#0099FF','border-radius':'0px','font-size':'16px'});
	});
	//精品推荐游戏图片效果
	$(".jptj").mouseenter(function(){
		$(this).find("img").animate({'margin':'-5%','width':'110%','height':'110%','opacity':'0.8'});
		//$(this).find(".jptj2").show().animate({'height':'330px','width':'220px','margin':'0px','opacity':'0.4'});
		$(this).find(".jptj2").show().animate({'margin-top':'280px','height':'50px','width':'220px','opacity':'0.8'});
	});
	$(".jptj").mouseleave(function(){
		$(this).find("img").animate({'margin':'0px','width':'100%','height':'100%','opacity':'1'});
		//$(this).find(".jptj2").animate({'height':'0px','width':'0px','margin':'150px 110px','opacity':'0'});
		$(this).find(".jptj2").animate({'margin-top':'330px','height':'0px','width':'220px','opacity':'0'});
	});
	//左边广告背景颜色
	$(".b_gg").html("<img src='/images/gg/gg4.jpg' />"); //广告位招租<br />宽：950px 高:100px 500元/月<br />投广告请联系QQ：200467");
	$(".b_gg").mouseenter(function(){
		$(this).animate({'background-color':'#FF9966','color':'#FFFFFF','opacity':'1'});
	});
	$(".b_gg").mouseleave(function(){
		$(this).animate({'background-color':'#FFFFFF','color':'#000000','opacity':'0.7'});
	});
	//右边广告背景颜色
	/*$(".r_gg").html("广告位招租<br />宽：240px 高:140px 100元/月<br />投广告请联系QQ：200467");
	$(".r_gg").mouseenter(function(){
		$(this).animate({'background-color':'#9933FF','color':'#FFFFFF'});
	});
	$(".r_gg").mouseleave(function(){
		$(this).animate({'background-color':'#FFFFFF','color':'#000000'});
	});*/
	$(".r_gg2").mouseenter(function(){
		$(this).find("img").animate({'margin':'-5%','width':'110%','height':'110%','border-radius':'5px'});
	});
	$(".r_gg2").mouseleave(function(){
		$(this).find("img").animate({'margin':'0px','width':'100%','height':'100%','border-radius':'5px'});
	});
	$(".r_gg3").mouseenter(function(){
		$(this).find("img").animate({'margin':'-5%','width':'110%','height':'110%','border-radius':'5px'});
	});
	$(".r_gg3").mouseleave(function(){
		$(this).find("img").animate({'margin':'0px','width':'100%','height':'100%','border-radius':'5px'});
	});
	//友链
	$(".link").find("div").mouseenter(function(){
		$(this).animate({'background-color':'#cccccc'});
	});
	$(".link").find("div").mouseleave(function(){
		$(this).animate({'background-color':'#EEEEEE'});
	});
	//翻页列表
	$(".youxipage2").mouseenter(function(){
		$(this).animate({'background-color':'#FF9966'});
	});
	$(".youxipage2").mouseleave(function(){
		$(this).animate({'background-color':'#FFFFFF'});
	});
	//游戏列表单个游戏
	$(".youxi").mouseenter(function(){
		$(this).animate({'background-color':'#66CCFF','border-radius':'5px'});
		$(this).find("img").animate({'margin':'-5%','width':'110%','height':'110%'});
	});
	$(".youxi").mouseleave(function(){
		$(this).animate({'background-color':'#FFFFFF','border-radius':'0px'});
		$(this).find("img").animate({'margin':'0px','width':'100%','height':'100%'});
	});
	//快速查找游戏
	$(".youxilx").find("a").mouseenter(function(){
		$(this).animate({'background-color':'orange'});
	});
	$(".youxilx").find("a").mouseleave(function(){
		$(this).animate({'background-color':'#EEEEEE'});
	});
	//玩家相片
	$(".w_p").mouseenter(function(){
		$(this).animate({'background-color':'#FFCC99'});
		$(this).find("img").animate({'border-radius':'5px'});
	});
	$(".w_p").mouseleave(function(){
		$(this).animate({'background-color':'#EEEEEE'});
		$(this).find("img").animate({'border-radius':'50px'});
	});
		//分页的显示效果
	$(".page2").mouseenter(function(){
		$(this).animate({'border-radius':'5px','background-color':'#66CCFF'});
	});
	$(".page2").mouseleave(function(){
		$(this).animate({'border-radius':'20px','background-color':'#CCCCCC'});
	});
	//图片的显示效果
	$(".pic2").mouseenter(function(){
		$(this).animate({'border-radius':'5px'});
	});
	$(".pic2").mouseleave(function(){
		$(this).animate({'border-radius':'20px'});
	});
});
